--========== EXPLORATORY DATA ANALYSIS =============

--1) DATABASE EXPLORATION:

--- Explore All objects in the database

SELECT * FROM INFORMATION_SCHEMA.TABLES
GO


-- Explore  All Columns in the database

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'



--2) DIMENSIONS EXPLORATIONS:

--- Explore all countries our csutomers come from.

SELECT DISTINCT country from gold.dim_customers


-- Explore All Categories "The major divisions"

SELECT DISTINCT category, subcategory, product_name from gold.dim_products order by 1,2,3
GO


-- 3) DATE EXPLORATION 

-- Find the date of the first and last order

SELECT MIN(order_date) as first_order, MAX(order_date) as latest_order,
DATEDIFF(year, min(order_date),max(order_date)) as  order_range_years	
FROM gold.fact_sales
GO

--- find youngest and oldest customer

SELECT 
	datediff(year,MIN(birth_date),getdate()) as oldest_customer,
	datediff(year,MAX(birth_date),getdate()) as youngest_customer
FROM gold.dim_customers
go



---4) Measures Exploration:

---- Find Total Sales

select sum(sales_amount) as total_sales
from gold.fact_sales
go

---- find how many items are sold

select sum(quantity) As total_quantity
from gold.fact_sales
go


---- find average selling price

select avg(price) As average_selling_price
from gold.fact_sales
go


---- find total number of orders

select count(DISTINCT order_number) As number_of_orders
from gold.fact_sales
go


---- find total number of products

select count(product_key) as number_of_products
from gold.dim_products
go

---- find total number of customers

select count(distinct customer_key) as number_of_customers
from gold.dim_customers
go

---- find total number of customers who placed an order

select count(distinct customer_key)
from gold.fact_sales
go



--- Generate a Report that shows all key metrics of the business

select 'Total sales' as measure_name, sum(sales_amount) as measure_value from gold.fact_sales
union all
select 'Total quantity' as measure_name, sum(quantity) as measure_value from gold.fact_sales
union all
select 'Average price' as measure_name, avg(price) as measure_value from gold.fact_sales
union all
select 'Nr of orders' as measure_name, count(DISTINCT order_number) as measure_value from gold.fact_sales
union all
select 'Nr of products' as measure_name, count(product_key) as measure_value from gold.dim_products
union all
select 'Nr of customers' as measure_name, count(distinct customer_id) as measure_value from gold.dim_customers


-- 5) Magnitude Analysis
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;


 -- 6) Ranking Analysis

 -- which 5 products generate the highest revenue


 select top 5
        pr.product_name,
        sum(fs.sales_amount) as Revenue   
 from gold.fact_sales fs
 left join gold.dim_products pr
 on fs.product_key = pr.product_key
 group by pr.product_name
 order by Revenue desc


 --- what are the worst 5 performing products in terms of sales

  select top 5
        pr.product_name,
        sum(fs.sales_amount) as Revenue   
 from gold.fact_sales fs
 left join gold.dim_products pr
 on fs.product_key = pr.product_key
 group by pr.product_name
 order by Revenue 



 -- which 5 sub categories generate the highest revenue

 

 select top 5
        pr.subcategory,
        sum(fs.sales_amount) as Revenue   
 from gold.fact_sales fs
 left join gold.dim_products pr
 on fs.product_key = pr.product_key
 group by subcategory
 order by Revenue desc



 select * from (
 select pr.product_name,
        sum(fs.sales_amount) as Revenue,
        row_number() over(order by sum(sales_amount) desc) as rank_products
 from gold.fact_sales fs
 left join gold.dim_products pr
 on fs.product_key = pr.product_key
 group by pr.product_name

 ) t
 where rank_products <=5
 

 --- Top 10 customers who have generated the highest revenue
select top 10
    c.customer_key,
    c.first_name,
    c.last_name,
    sum(fs.sales_amount) as revenue
from gold.fact_sales fs
left join gold.dim_customers c
on c.customer_key = fs.customer_key
group by c.customer_key,c.first_name,c.last_name
order by revenue desc

--- top 3 customers with fewest orders placed

select top 3
    c.customer_key,
    c.first_name,
    c.last_name,
    count(distinct fs.order_number) as no_of_orders 
from gold.fact_sales fs
left join gold.dim_customers c
on c.customer_key = fs.customer_key
group by c.customer_key,c.first_name,c.last_name
order by no_of_orders 




